apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-oiy0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kqjg-tenant/rhtap-demo-app/hacbs-test-project-oiy0@sha256:56f03c14171858f1083d05d0004688fee5db4f437331614b6929bae7f71c8ce1
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
